In [1]:
import pandas as pd
import numpy
import xlrd
data = pd.read_excel('4_Cluster Analysis_Data.xlsx', sheet_name="Transactions")

In [2]:
table = pd.pivot(data, index='Offer #', columns="Customer Last Name", values="Offer #")

In [3]:
table = table.fillna(0)
table = table.astype(int)
table

Customer Last Name,Adams,Allen,Anderson,Bailey,Baker,Barnes,Bell,Bennett,Brooks,Brown,...,Turner,Walker,Ward,Watson,White,Williams,Wilson,Wood,Wright,Young
Offer #,,,,,,,,,,,,,,,,,,,,,
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2,0,0,0,0,0,0,2,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,3,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,4,0,4,0,0,0,0,0,4,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,6,0,0,0,0,0,0,0,6,6
7,0,0,0,7,7,0,0,0,0,7,...,0,0,0,7,0,0,0,0,0,0
8,0,0,0,0,0,0,0,8,8,0,...,0,0,0,0,0,0,8,0,0,0
9,0,9,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,9
10,0,0,0,0,10,10,0,0,0,0,...,0,0,0,0,0,0,0,10,0,0
11,0,0,0,0,0,0,0,0,11,0,...,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,14,0,0,14,0,0
15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,15
16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,0,0,0,0,0,0,17,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,18,0,0,0,0,0,0,0,0,0,...,0,18,0,0,0,18,0,0,0,0
19,0,0,0,0,19,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,0,0,0,0,0,21,0,0,0,0,...,0,0,0,0,0,0,0,0,21,0
22,0,0,0,0,0,22,0,0,22,0,...,0,0,0,0,22,22,0,0,0,22
23,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,0,0,24,0,0,0,24,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,25,0,0,0,0,0
26,0,0,26,0,0,0,26,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,0,27,0,0,0,0,0,0,0,0,...,27,0,0,0,0,0,0,0,27,0
28,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,29,0,0,0,0,0,0,29,0,29,...,0,29,0,29,0,0,0,0,0,0
30,30,0,0,30,0,0,0,0,0,30,...,0,0,0,0,30,0,30,0,0,0
31,0,0,0,0,31,31,0,0,0,0,...,31,0,0,0,0,31,0,31,0,31
32,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,32

In [4]:
table[table>0]=1
table

Customer Last Name,Adams,Allen,Anderson,Bailey,Baker,Barnes,Bell,Bennett,Brooks,Brown,...,Turner,Walker,Ward,Watson,White,Williams,Wilson,Wood,Wright,Young
Offer #,,,,,,,,,,,,,,,,,,,,,
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,1,0,1,0,0,0,0,0,1,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,1
7,0,0,0,1,1,0,0,0,0,1,...,0,0,0,1,0,0,0,0,0,0
8,0,0,0,0,0,0,0,1,1,0,...,0,0,0,0,0,0,1,0,0,0
9,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
10,0,0,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
11,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,1,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,1,0,0,0,0
19,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
22,0,0,0,0,0,1,0,0,1,0,...,0,0,0,0,1,1,0,0,0,1
23,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,0,0,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
26,0,0,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,0,1,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
28,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,1,0,0,0,0,0,0,1,0,1,...,0,1,0,1,0,0,0,0,0,0
30,1,0,0,1,0,0,0,0,0,1,...,0,0,0,0,1,0,1,0,0,0
31,0,0,0,0,1,1,0,0,0,0,...,1,0,0,0,0,1,0,1,0,1
32,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [5]:
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

In [6]:
kmeans3 = KMeans(n_clusters=3, max_iter=300).fit(table.T)
sil_3 = silhouette_score(table.T, kmeans3.labels_, metric='euclidean')

kmeans4 = KMeans(n_clusters=4, max_iter=300).fit(table.T)
sil_4 = silhouette_score(table.T, kmeans4.labels_, metric='euclidean')

kmeans5 = KMeans(n_clusters=5, max_iter=300).fit(table.T)
sil_5 = silhouette_score(table.T, kmeans5.labels_, metric='euclidean')

In [7]:
sil_list = [sil_3,sil_4,sil_5]
print(sil_list)
print(sil_list.index(max(sil_list))+3)

[0.11983176694269196, 0.12857977968680218, 0.12447307057103224]
4

In [8]:
CList = [[0 for k in range(4)] for i in range(len(table.index))]
for i, vi in enumerate(table.index):
    for j, vj in enumerate(table.columns):
        CList[i][kmeans4.labels_[j]] += table.loc[vi][vj]

In [9]:
cluster_table = pd.DataFrame(data=CList, index=table.index, columns=['Cluster 1','Cluster 2','Cluster 3','Cluster 4'])

In [10]:
cluster_table

         Cluster 1  Cluster 2  Cluster 3  Cluster 4
Offer #
1                5          5          0          0
2                3          2          0          5
3                2          4          0          0
4                9          3          0          0
5                4          0          0          0
6                5          6          1          0
7                4          3         12          0
8                1          3         16          0
9                8          2          0          0
10               4          2          1          0
11               8          5          0          0
12               3          2          0          0
13               0          0          6          0
14               6          3          0          0
15               3          3          0          0
16               5          0          0          0
17               0          0          0          7
18               1          1         12          0
19               2          3          0          0
20               6          0          0          0
21               2          2          0          0
22               1         20          0          0
23               3          2          0          0
24               0          0          0         12
25               4          2          0          0
26               6          0          0          9
27               5          3          1          0
28               3          2          1          0
29               1          0         16          0
30               2          4         16          0
31              10          7          0          0
32               3          1          0          0

In [12]:
offInfo = pd.read_excel('4_Cluster Analysis_Data.xlsx', sheet_name="OfferInformation")

In [13]:
offInfo

,Offer #,Campaign,Varietal,Minimum Qty (kg),Discount (%),Origin,Past Peak
0,1,January,Malbec,72,56,France,False
1,2,January,Pinot Noir,72,17,France,False
2,3,February,Espumante,144,32,Oregon,True
3,4,February,Champagne,72,48,France,True
4,5,February,Cabernet Sauvignon,144,44,New Zealand,True
5,6,March,Prosecco,144,86,Chile,False
6,7,March,Prosecco,6,40,Australia,True
7,8,March,Espumante,6,45,South Africa,False
8,9,April,Chardonnay,144,57,Chile,False
9,10,April,Prosecco,72,52,California,False
10,11,May,Champagne,72,85,France,False
11,12,May,Prosecco,72,83,Australia,False
12,13,May,Merlot,6,43,Chile,False
13,14,June,Merlot,72,64,Chile,False
14,15,June,Cabernet Sauvignon,144,19,Italy,False
15,16,June,Merlot,72,88,California,False
16,17,July,Pinot Noir,12,47,Germany,False
17,18,July,Espumante,6,50,Oregon,False
18,19,July,Champagne,12,66,Germany,False
19,20,August,Cabernet Sauvignon,72,82,Italy,False
20,21,August,Champagne,12,50,California,False
21,22,August,Champagne,72,63,France,False
22,23,September,Chardonnay,144,39,South Africa,False
23,24,September,Pinot Noir,6,34,Italy,False
24,25,October,Cabernet Sauvignon,72,59,Oregon,True
25,26,October,Pinot Noir,144,83,Australia,False
26,27,October,Champagne,72,88,New Zealand,False
27,28,November,Cabernet Sauvignon,12,56,France,True
28,29,November,Pinot Grigio,6,87,France,False
29,30,December,Malbec,6,54,France,False
30,31,December,Champagne,72,89,France,False
31,32,December,Cabernet Sauvignon,72,45,Germany,True

In [14]:
CTable = pd.merge(offInfo, cluster_table, on="Offer #")

In [15]:
CTable

,Offer #,Campaign,Varietal,Minimum Qty (kg),Discount (%),Origin,Past Peak,Cluster 1,Cluster 2,Cluster 3,Cluster 4
0,1,January,Malbec,72,56,France,False,5,5,0,0
1,2,January,Pinot Noir,72,17,France,False,3,2,0,5
2,3,February,Espumante,144,32,Oregon,True,2,4,0,0
3,4,February,Champagne,72,48,France,True,9,3,0,0
4,5,February,Cabernet Sauvignon,144,44,New Zealand,True,4,0,0,0
5,6,March,Prosecco,144,86,Chile,False,5,6,1,0
6,7,March,Prosecco,6,40,Australia,True,4,3,12,0
7,8,March,Espumante,6,45,South Africa,False,1,3,16,0
8,9,April,Chardonnay,144,57,Chile,False,8,2,0,0
9,10,April,Prosecco,72,52,California,False,4,2,1,0
10,11,May,Champagne,72,85,France,False,8,5,0,0
11,12,May,Prosecco,72,83,Australia,False,3,2,0,0
12,13,May,Merlot,6,43,Chile,False,0,0,6,0
13,14,June,Merlot,72,64,Chile,False,6,3,0,0
14,15,June,Cabernet Sauvignon,144,19,Italy,False,3,3,0,0
15,16,June,Merlot,72,88,California,False,5,0,0,0
16,17,July,Pinot Noir,12,47,Germany,False,0,0,0,7
17,18,July,Espumante,6,50,Oregon,False,1,1,12,0
18,19,July,Champagne,12,66,Germany,False,2,3,0,0
19,20,August,Cabernet Sauvignon,72,82,Italy,False,6,0,0,0
20,21,August,Champagne,12,50,California,False,2,2,0,0
21,22,August,Champagne,72,63,France,False,1,20,0,0
22,23,September,Chardonnay,144,39,South Africa,False,3,2,0,0
23,24,September,Pinot Noir,6,34,Italy,False,0,0,0,12
24,25,October,Cabernet Sauvignon,72,59,Oregon,True,4,2,0,0
25,26,October,Pinot Noir,144,83,Australia,False,6,0,0,9
26,27,October,Champagne,72,88,New Zealand,False,5,3,1,0
27,28,November,Cabernet Sauvignon,12,56,France,True,3,2,1,0
28,29,November,Pinot Grigio,6,87,France,False,1,0,16,0
29,30,December,Malbec,6,54,France,False,2,4,16,0
30,31,December,Champagne,72,89,France,False,10,7,0,0
31,32,December,Cabernet Sauvignon,72,45,Germany,True,3,1,0,0

In [16]:
CTable.sort_values("Cluster 1", ascending=False)

,Offer #,Campaign,Varietal,Minimum Qty (kg),Discount (%),Origin,Past Peak,Cluster 1,Cluster 2,Cluster 3,Cluster 4
30,31,December,Champagne,72,89,France,False,10,7,0,0
3,4,February,Champagne,72,48,France,True,9,3,0,0
8,9,April,Chardonnay,144,57,Chile,False,8,2,0,0
10,11,May,Champagne,72,85,France,False,8,5,0,0
13,14,June,Merlot,72,64,Chile,False,6,3,0,0
25,26,October,Pinot Noir,144,83,Australia,False,6,0,0,9
19,20,August,Cabernet Sauvignon,72,82,Italy,False,6,0,0,0
15,16,June,Merlot,72,88,California,False,5,0,0,0
26,27,October,Champagne,72,88,New Zealand,False,5,3,1,0
0,1,January,Malbec,72,56,France,False,5,5,0,0
5,6,March,Prosecco,144,86,Chile,False,5,6,1,0
9,10,April,Prosecco,72,52,California,False,4,2,1,0
6,7,March,Prosecco,6,40,Australia,True,4,3,12,0
24,25,October,Cabernet Sauvignon,72,59,Oregon,True,4,2,0,0
4,5,February,Cabernet Sauvignon,144,44,New Zealand,True,4,0,0,0
27,28,November,Cabernet Sauvignon,12,56,France,True,3,2,1,0
22,23,September,Chardonnay,144,39,South Africa,False,3,2,0,0
31,32,December,Cabernet Sauvignon,72,45,Germany,True,3,1,0,0
1,2,January,Pinot Noir,72,17,France,False,3,2,0,5
14,15,June,Cabernet Sauvignon,144,19,Italy,False,3,3,0,0
11,12,May,Prosecco,72,83,Australia,False,3,2,0,0
18,19,July,Champagne,12,66,Germany,False,2,3,0,0
20,21,August,Champagne,12,50,California,False,2,2,0,0
29,30,December,Malbec,6,54,France,False,2,4,16,0
2,3,February,Espumante,144,32,Oregon,True,2,4,0,0
17,18,July,Espumante,6,50,Oregon,False,1,1,12,0
21,22,August,Champagne,72,63,France,False,1,20,0,0
7,8,March,Espumante,6,45,South Africa,False,1,3,16,0
28,29,November,Pinot Grigio,6,87,France,False,1,0,16,0
23,24,September,Pinot Noir,6,34,Italy,False,0,0,0,12
12,13,May,Merlot,6,43,Chile,False,0,0,6,0
16,17,July,Pinot Noir,12,47,Germany,False,0,0,0,7

In [17]:
CTable.sort_values("Cluster 2", ascending=False)

,Offer #,Campaign,Varietal,Minimum Qty (kg),Discount (%),Origin,Past Peak,Cluster 1,Cluster 2,Cluster 3,Cluster 4
21,22,August,Champagne,72,63,France,False,1,20,0,0
30,31,December,Champagne,72,89,France,False,10,7,0,0
5,6,March,Prosecco,144,86,Chile,False,5,6,1,0
10,11,May,Champagne,72,85,France,False,8,5,0,0
0,1,January,Malbec,72,56,France,False,5,5,0,0
29,30,December,Malbec,6,54,France,False,2,4,16,0
2,3,February,Espumante,144,32,Oregon,True,2,4,0,0
3,4,February,Champagne,72,48,France,True,9,3,0,0
18,19,July,Champagne,12,66,Germany,False,2,3,0,0
26,27,October,Champagne,72,88,New Zealand,False,5,3,1,0
14,15,June,Cabernet Sauvignon,144,19,Italy,False,3,3,0,0
6,7,March,Prosecco,6,40,Australia,True,4,3,12,0
13,14,June,Merlot,72,64,Chile,False,6,3,0,0
7,8,March,Espumante,6,45,South Africa,False,1,3,16,0
22,23,September,Chardonnay,144,39,South Africa,False,3,2,0,0
9,10,April,Prosecco,72,52,California,False,4,2,1,0
27,28,November,Cabernet Sauvignon,12,56,France,True,3,2,1,0
1,2,January,Pinot Noir,72,17,France,False,3,2,0,5
8,9,April,Chardonnay,144,57,Chile,False,8,2,0,0
24,25,October,Cabernet Sauvignon,72,59,Oregon,True,4,2,0,0
20,21,August,Champagne,12,50,California,False,2,2,0,0
11,12,May,Prosecco,72,83,Australia,False,3,2,0,0
31,32,December,Cabernet Sauvignon,72,45,Germany,True,3,1,0,0
17,18,July,Espumante,6,50,Oregon,False,1,1,12,0
23,24,September,Pinot Noir,6,34,Italy,False,0,0,0,12
19,20,August,Cabernet Sauvignon,72,82,Italy,False,6,0,0,0
25,26,October,Pinot Noir,144,83,Australia,False,6,0,0,9
15,16,June,Merlot,72,88,California,False,5,0,0,0
28,29,November,Pinot Grigio,6,87,France,False,1,0,16,0
12,13,May,Merlot,6,43,Chile,False,0,0,6,0
4,5,February,Cabernet Sauvignon,144,44,New Zealand,True,4,0,0,0
16,17,July,Pinot Noir,12,47,Germany,False,0,0,0,7

In [18]:
CTable.sort_values("Cluster 3", ascending=False)

,Offer #,Campaign,Varietal,Minimum Qty (kg),Discount (%),Origin,Past Peak,Cluster 1,Cluster 2,Cluster 3,Cluster 4
29,30,December,Malbec,6,54,France,False,2,4,16,0
28,29,November,Pinot Grigio,6,87,France,False,1,0,16,0
7,8,March,Espumante,6,45,South Africa,False,1,3,16,0
17,18,July,Espumante,6,50,Oregon,False,1,1,12,0
6,7,March,Prosecco,6,40,Australia,True,4,3,12,0
12,13,May,Merlot,6,43,Chile,False,0,0,6,0
9,10,April,Prosecco,72,52,California,False,4,2,1,0
5,6,March,Prosecco,144,86,Chile,False,5,6,1,0
27,28,November,Cabernet Sauvignon,12,56,France,True,3,2,1,0
26,27,October,Champagne,72,88,New Zealand,False,5,3,1,0
23,24,September,Pinot Noir,6,34,Italy,False,0,0,0,12
21,22,August,Champagne,72,63,France,False,1,20,0,0
22,23,September,Chardonnay,144,39,South Africa,False,3,2,0,0
0,1,January,Malbec,72,56,France,False,5,5,0,0
24,25,October,Cabernet Sauvignon,72,59,Oregon,True,4,2,0,0
25,26,October,Pinot Noir,144,83,Australia,False,6,0,0,9
19,20,August,Cabernet Sauvignon,72,82,Italy,False,6,0,0,0
30,31,December,Champagne,72,89,France,False,10,7,0,0
20,21,August,Champagne,12,50,California,False,2,2,0,0
16,17,July,Pinot Noir,12,47,Germany,False,0,0,0,7
18,19,July,Champagne,12,66,Germany,False,2,3,0,0
1,2,January,Pinot Noir,72,17,France,False,3,2,0,5
15,16,June,Merlot,72,88,California,False,5,0,0,0
14,15,June,Cabernet Sauvignon,144,19,Italy,False,3,3,0,0
13,14,June,Merlot,72,64,Chile,False,6,3,0,0
11,12,May,Prosecco,72,83,Australia,False,3,2,0,0
10,11,May,Champagne,72,85,France,False,8,5,0,0
8,9,April,Chardonnay,144,57,Chile,False,8,2,0,0
4,5,February,Cabernet Sauvignon,144,44,New Zealand,True,4,0,0,0
3,4,February,Champagne,72,48,France,True,9,3,0,0
2,3,February,Espumante,144,32,Oregon,True,2,4,0,0
31,32,December,Cabernet Sauvignon,72,45,Germany,True,3,1,0,0

In [19]:
CTable.sort_values("Cluster 4", ascending=False)

,Offer #,Campaign,Varietal,Minimum Qty (kg),Discount (%),Origin,Past Peak,Cluster 1,Cluster 2,Cluster 3,Cluster 4
23,24,September,Pinot Noir,6,34,Italy,False,0,0,0,12
25,26,October,Pinot Noir,144,83,Australia,False,6,0,0,9
16,17,July,Pinot Noir,12,47,Germany,False,0,0,0,7
1,2,January,Pinot Noir,72,17,France,False,3,2,0,5
30,31,December,Champagne,72,89,France,False,10,7,0,0
29,30,December,Malbec,6,54,France,False,2,4,16,0
28,29,November,Pinot Grigio,6,87,France,False,1,0,16,0
27,28,November,Cabernet Sauvignon,12,56,France,True,3,2,1,0
26,27,October,Champagne,72,88,New Zealand,False,5,3,1,0
24,25,October,Cabernet Sauvignon,72,59,Oregon,True,4,2,0,0
22,23,September,Chardonnay,144,39,South Africa,False,3,2,0,0
21,22,August,Champagne,72,63,France,False,1,20,0,0
20,21,August,Champagne,12,50,California,False,2,2,0,0
19,20,August,Cabernet Sauvignon,72,82,Italy,False,6,0,0,0
18,19,July,Champagne,12,66,Germany,False,2,3,0,0
17,18,July,Espumante,6,50,Oregon,False,1,1,12,0
0,1,January,Malbec,72,56,France,False,5,5,0,0
15,16,June,Merlot,72,88,California,False,5,0,0,0
14,15,June,Cabernet Sauvignon,144,19,Italy,False,3,3,0,0
13,14,June,Merlot,72,64,Chile,False,6,3,0,0
12,13,May,Merlot,6,43,Chile,False,0,0,6,0
11,12,May,Prosecco,72,83,Australia,False,3,2,0,0
10,11,May,Champagne,72,85,France,False,8,5,0,0
9,10,April,Prosecco,72,52,California,False,4,2,1,0
8,9,April,Chardonnay,144,57,Chile,False,8,2,0,0
7,8,March,Espumante,6,45,South Africa,False,1,3,16,0
6,7,March,Prosecco,6,40,Australia,True,4,3,12,0
5,6,March,Prosecco,144,86,Chile,False,5,6,1,0
4,5,February,Cabernet Sauvignon,144,44,New Zealand,True,4,0,0,0
3,4,February,Champagne,72,48,France,True,9,3,0,0
2,3,February,Espumante,144,32,Oregon,True,2,4,0,0
31,32,December,Cabernet Sauvignon,72,45,Germany,True,3,1,0,0

In [21]:
kmeans4

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=4, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)